name 'first_cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures first_cookbook'
long_description 'Installs/Configures first_cookbook'
version '0.1.0'
